require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/*

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/LineLength:
  Max: 120
  Exclude:
    - db/**/*.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: False

RSpec/NestedGroups:
  Max: 5

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - config/routes.rb

Style/SafeNavigation:
  Enabled: false
